# -*- coding: utf-8 -*-
"""Employee_salary_pridiction .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OSNC9sSfDqLGcSnv8SDdb7l1clZeByGy
"""

import pandas as pd
data  = pd.read_csv("/content/adult/adult_3.csv")



data

data.shape

data.head(7)

data.tail(7)

data.isna()

data.isna().sum()

print(data.occupation.value_counts())

print(data.gender.value_counts())

print(data['education'].value_counts())

print(data['education'].value_counts())

print(data.occupation.replace({'?':'Others'}))

data.occupation.replace({'?':'Others'},inplace=True)
print(data.occupation.value_counts())

data.workclass.replace({'?':'Not Listed'}, inplace=True)
print(data.workclass.value_counts())

data=data[data['workclass']!='Without-pay']
data=data[data['workclass']!='Never-worked']

print(data.workclass.value_counts())

data.shape

print(data['education'].value_counts())

data=data[data['education']!='5th-6th']
data=data[data['education']!='Preschoold']
data=data[data['education']!='1st-4th']

print(data['education'].value_counts())

data.shape

data

data.drop(columns=['education'],inplace=True)

data

import matplotlib.pyplot as plt
plt.boxplot(data['age'])
plt.show()

data= data[(data['age']<=75) & (data['age']>=17)]
plt.boxplot(data['age'])
plt.show()

"""#ncoseing
#Label n codeing
"""

from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
data['workclass']=encoder.fit_transform(data['workclass'])